### ISSUE TITLE
Req. #002 - Inicio de Sesión

### ISSUE THREAD

**Issue by EddyEscalanteU** [EddyEscalanteU/ingenieria-software-upc-8-2023#2]
DESCRIPTION
Quien=>	El usuario visita la AppWeb.
Que=>		El usuario Ingresa sus Credenciales (Contraseña y usuario)
Por Qué=>	Para Lograr ingresar al Sistema.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=>	El Usuario visita la App Web.
Cuando=>	El Usuario Ingrese sus credenciales.
Entonces=>	La App Web Retornara que su Ingreso Fue exitoso.
CRITERIOS DE ACEPTACIÓN 2:
Dado=>	El Usuario en el Sitio AppWeb.
Cuando=>	El Usuario Ingrese sus credenciales (erróneos)
Entonces=>	La AppWeb Retornara que su Usuario o Contraseña no son correctos.
CRITERIOS DE ACEPTACIÓN 3:
Dado=>	El Usuario en el Sitio Web.
Cuando=>	El Usuario Ingrese sus credenciales (erróneos por 5 veces consecutiva)
Entonces=>	La AppWeb Retornara que su Usuario o Contraseña no son correctos y le dará una captcha para continuar el registro

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=> El Usuario visita la App Web.
Cuando=> El Usuario Ingrese sus credenciales.
Entonces=> La App Web Retornara que su Ingreso Fue exitoso.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 3:
Dado=> El Usuario en el Sitio Web.
Cuando=> El Usuario Ingrese sus credenciales (erróneos por 5 veces consecutiva)
Entonces=> La AppWeb Retornara que su Usuario o Contraseña no son correctos y le dará una captcha para continuar el registro
