### ISSUE TITLE
Req. #028 - Reporte de Carrito de Compra

### ISSUE THREAD

**Issue by EddyEscalanteU** [EddyEscalanteU/ingenieria-software-upc-8-2023#28]
Descripción:
Quién: El administrador accede a la aplicación web con sus credenciales.
Qué: Genera un reporte del carrito de compra desde la opción "Reporte de Carrito de Compra" en la aplicación.
Por qué: Para analizar y comprender el comportamiento de compra de los clientes y mejorar la experiencia de compra en la tienda en línea.

**Comment by ChristianCRJ** [comment]
Criterios de Aceptación 1:
Dado: Un administrador dentro de la aplicación web de la tienda.
Cuando: Acceda a la opción "Reporte de Carrito de Compra".
Entonces: La aplicación web le mostrará una lista de carritos de compra activos con detalles como el nombre del cliente, los productos en el carrito, la cantidad de productos y el valor total.

**Comment by ChristianCRJ** [comment]
Criterios de Aceptación 2:
Dado: Un administrador dentro de la aplicación web de la tienda.
Cuando: Acceda a la opción "Reporte de Carrito de Compra".
Entonces: La aplicación web permitirá al administrador filtrar los carritos de compra por fecha, cliente o estado del carrito (activo).

**Comment by ChristianCRJ** [comment]
Criterios de Aceptación 3:
Dado: Un administrador dentro de la aplicación web de la tienda.
Cuando: Acceda a la opción "Reporte de Carrito de Compra".
Entonces: La aplicación web generará un informe descargable en formato PDF o CSV que contendrá la información de los carritos de compra según los filtros aplicados.

**Comment by ChristianCRJ** [comment]
Criterios de Aceptación 4:
Dado: Un administrador dentro de la aplicación web de la tienda.
Cuando: Acceda a la opción "Reporte de Carrito de Compra".
Entonces: La aplicación web enviará una notificación al administrador cuando el informe esté listo para su descarga, con un enlace directo para acceder al informe generado.
