### ISSUE TITLE
Req. #003 - Cambio de Contraseña

### ISSUE THREAD

**Issue by EddyEscalanteU** [EddyEscalanteU/ingenieria-software-upc-8-2023#3]
DESCRIPTION
Quien=>	El Usuario entra a la AppWeb con su Usuario y Contraseña
Que=>		Ingresa a la opción “Cambio de contraseña”.
Por Qué=>	Para así poder Cambiar la Contraseña del Usuario

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=> 	Un Usuario dentro de la AppWeb
Cuando=> 	Ingrese la Actual y Nueva Contraseña.
Entonces=> 	La AppWeb retornara que su Cambio de Contraseña fue Exitoso.
CRITERIOS DE ACEPTACIÓN 2:
Dado=> 	Un Usuario dentro de la AppWeb
Cuando=> 	Ingrese erróneamente la Actual Contraseña y Nueva Contraseña.
Entonces=> 	La AppWeb retornará que la contraseña ingresada no es Correcta.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=> Un Usuario dentro de la AppWeb
Cuando=> Ingrese la Actual y Nueva Contraseña.
Entonces=> La AppWeb retornara que su Cambio de Contraseña fue Exitoso.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 2:
Dado=> Un Usuario dentro de la AppWeb
Cuando=> Ingrese erróneamente la Actual Contraseña y Nueva Contraseña.
Entonces=> La AppWeb retornará que la contraseña ingresada no es Correcta.
