### ISSUE TITLE
Req. #004 - Olvide la contraseña

### ISSUE THREAD

**Issue by EddyEscalanteU** [EddyEscalanteU/ingenieria-software-upc-8-2023#4]
DESCRIPTION
Quien=>	El Usuario Visita la página
Que=>		Entra en la opción “¿Olvidó su contraseña?”.
Por Qué=>	Para Resetear la Contraseña del Usuario

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=>	Que usuario olvidó la contraseña.
Cuando=>	Envía solicitud de reseteo de contraseña, al correo registrado del usuario.
Entonces=>	La Appweb envía un correo electrónico con un link de reseteo de contraseña.
CRITERIOS DE ACEPTACIÓN 2:
Dado=>	Que usuario olvidó la contraseña.
Cuando=>	Envía solicitud de reseteo de contraseña, al correo erróneo.
Entonces=>	La AppWeb informará que el Correo no existe.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 1:
Dado=> Que usuario olvidó la contraseña.
Cuando=> Envía solicitud de reseteo de contraseña, al correo registrado del usuario.
Entonces=> La Appweb envía un correo electrónico con un link de reseteo de contraseña.

**Comment by CarlosEdgar27** [comment]
CRITERIOS DE ACEPTACIÓN 2:
Dado=> Que usuario olvidó la contraseña.
Cuando=> Envía solicitud de reseteo de contraseña, al correo erróneo.
Entonces=> La AppWeb informará que el Correo no existe.
